### ISSUE TITLE
getting articles that it's tags belong to a group

### ISSUE THREAD

**Issue by Xoshbin** [rtconner/laravel-tagging#157] opened 2018-11-08 10:13 UTC
Hi, Is there any method to grab all the articles that their tags belong to a group? something like below:

Article::withAnyGroup('Gardening');

**Comment by rtconner** [comment] 2019-03-20 03:32
Don't have that feature at this time. Sorry. I think you would just do a has many through relation.

**Comment by rtconner** [comment] 2019-03-20 03:52
Closing this as duplicate of https://github.com/rtconner/laravel-tagging/issues/110

That is a complex query as it turns out.

**Closed by rtconner** 2019-03-20 03:52 UTC

**Comment by Xoshbin** [comment] 2019-03-20 06:39
I could manage it that way. 
`$posts = Post::withAnyTag(\Conner\Tagging\Model\Tag::inGroup($tagGroupName)->get()->pluck('name')->toArray())->get();`
I know it's kinda slow but it's working for me and I need it.

**Comment by Xoshbin** [comment] 2022-02-23 19:32
As the project grows, this [method](https://github.com/rtconner/laravel-tagging/issues/157#issuecomment-474705739) is getting slower and slower, So I was asking if anyone knows any other way better than that. I would appreciate it.

`$posts = Post::withAnyTag(\Conner\Tagging\Model\Tag::inGroup($tagGroupName)->get()->pluck('name')->toArray())->get();`
