### ISSUE TITLE
Unable to publish config/migrations.

### ISSUE THREAD

**Issue by kevdotbadger** [rtconner/laravel-tagging#43] opened 2015-05-08 12:02 UTC
The original path `__DIR__.'/../../../config/tagging.php' => config_path('tagging.php'),` seems to be wrong. I had to change this in my basic setup to `_DIR__.'/../config/tagging.php' => config_path('tagging.php'),`.

**Comment by rtconner** [comment] 2015-05-08 14:57
Ah I think you are right. This is a bug caused by the move to PSR4. Thanks will fix asap.

**Comment by rtconner** [comment] 2015-05-08 15:30
Ok fixed in v 1.0.6

**Closed by rtconner** 2015-05-08 15:30 UTC

**Comment by kevdotbadger** [comment] 2015-05-09 10:55
Thanks.
